In [76]:
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import numpy as np

In [77]:
iris_data = load_iris()

In [78]:
X = iris_data.data
y = iris_data.target

X = preprocessing.scale(X)

In [79]:
# train test split (60 - 40)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 5)

In [80]:
print(f"Dimensions of X: {X.shape}, of y: {y.shape}")
print(f"Dimensions of X_train: {X_train.shape}, of y_train: {y_train.shape}")
print(f"Dimensions of X_test: {X_test.shape}, of y_test: {y_test.shape}")

Dimensions of X: (150, 4), of y: (150,)
Dimensions of X_train: (90, 4), of y_train: (90,)
Dimensions of X_test: (60, 4), of y_test: (60,)


In [81]:
# train using the training set
# penalty = 'l2' means use L2 regularization (squares of coefficients) 
log_reg = LogisticRegression(penalty='l2').fit(X_train, y_train)
log_reg.classes_

array([0, 1, 2])

In [82]:
log_reg.score(X_train, y_train)

0.9666666666666667

In [83]:
y_pred = log_reg.predict(X_test)

In [84]:
# same as (y_pred == y_test).mean()
log_reg.score(X_test, y_test)

0.95

In [87]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

target_names = ["setosa", "versicolor", "virginica"]
print(classification_report(y_test, y_pred, target_names=class_labels))

0.95
[[20  0  0]
 [ 0 20  1]
 [ 0  2 17]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        20
  versicolor       0.91      0.95      0.93        21
   virginica       0.94      0.89      0.92        19

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60

