In [1]:
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import numpy as np

In [2]:
iris_data = load_iris()

In [3]:
X = iris_data.data
y = iris_data.target

X = preprocessing.scale(X)

In [4]:
# train test split (60 - 40)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 5)

In [5]:
print(f"Dimensions of X: {X.shape}, of y: {y.shape}")
print(f"Dimensions of X_train: {X_train.shape}, of y_train: {y_train.shape}")
print(f"Dimensions of X_test: {X_test.shape}, of y_test: {y_test.shape}")

Dimensions of X: (150, 4), of y: (150,)
Dimensions of X_train: (90, 4), of y_train: (90,)
Dimensions of X_test: (60, 4), of y_test: (60,)


In [32]:
# use Stochastic Gradient Descent

nn = MLPClassifier(solver='sgd', hidden_layer_sizes=(5,), max_iter=2000, random_state=1).fit(X_train, y_train)

In [33]:
nn.score(X_train, y_train)

0.9444444444444444

In [44]:
y_pred = nn.predict(X_test)

In [40]:
# same as (y_pred == y_test).mean()
nn.score(X_test, y_test)

0.95

In [45]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

target_names = ["setosa", "versicolor", "virginica"]
print(classification_report(y_test, y_pred, target_names=target_names))

0.95
[[20  0  0]
 [ 0 19  2]
 [ 0  1 18]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        20
  versicolor       0.95      0.90      0.93        21
   virginica       0.90      0.95      0.92        19

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60

